workflows:
  ios-build:
    name: iOS Build for TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_VERSION: 'latest'
      flutter: '3.35.1'  # Deine lokale Version – definitiv 3.35.1
      xcode: latest
      cocoapods: 1.16.2
      groups:
        - appstore_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.thenewkid2022.bierlounge-tracker
    scripts:
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Flutter Clean
        script: flutter clean --verbose
      - name: Install Flutter dependencies
        script: flutter pub get --verbose
      - name: Update iOS Deployment Target
        script: |
          cd ios
          # Update Podfile platform
          sed -i.bak "s/platform :ios, '13.0'/platform :ios, '15.0'/g" Podfile
          # Update post_install in Podfile
          sed -i.bak "s/'IPHONEOS_DEPLOYMENT_TARGET' = '13.0'/'IPHONEOS_DEPLOYMENT_TARGET' = '15.0'/g" Podfile
          # Update project.pbxproj
          sed -i.bak 's/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' Runner.xcodeproj/project.pbxproj
          # Update Info.plist
          sed -i.bak 's/<string>13.0<\\/string>/<string>15.0<\\/string>/g' Runner/Info.plist
          # Cleanup backups
          rm -f Podfile.bak Runner.xcodeproj/project.pbxproj.bak Runner/Info.plist.bak
          # Update Pods repo
          pod repo update --verbose
      - name: Regenerate Flutter Configs After Update
        script: flutter pub get --verbose  # Neu: Regeneriert nach Target-Update
      - name: Update Flutter iOS Config
        script: flutter build ios --config-only --release --verbose > config_log.txt
      - name: Check Config Logs
        script: |
          cd ios/Flutter
          cat Generated.xcconfig
          echo 'Config Log:'
          cat ../../config_log.txt
      - name: Clean Xcode DerivedData
        script: |
          rm -rf $HOME/Library/Developer/Xcode/DerivedData/*
      - name: Debug Flutter Environment
        script: flutter doctor --verbose && flutter --version
      - name: Clean and Install Pods
        script: |
          cd ios
          pod deintegrate --verbose
          rm -rf Pods Podfile.lock
          pod install --repo-update --verbose
      - name: Fix Pod Configurations
        script: |
          cd ios/Flutter
          echo '#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"' >> Debug.xcconfig
          echo '#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"' >> Release.xcconfig
          echo '#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig"' >> Profile.xcconfig
      - name: Force iOS Build
        script: flutter build ios --release --verbose --no-codesign
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist --verbose --no-tree-shake-icons
      - name: Check Updated Files
        script: |
          ls -la ios/Runner.xcodeproj/
          cat ios/Runner.xcodeproj/project.pbxproj | grep IPHONEOS_DEPLOYMENT_TARGET
    artifacts:
      - build/ios/ipa/*.ipa
      - config_log.txt
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
