# Codemagic CI/CD Konfiguration f端r BierLounge Tracker
# Vereinfachte Konfiguration f端r iOS-Release-Builds
# Diese Konfiguration behebt "outdated build settings" Fehler

workflows:
  ios-build:
    name: iOS Build for TestFlight
    max_build_duration: 120
    instance_type: mac_pro_m1
    environment:
      vars:
        XCODE_VERSION: "15.4"
      flutter: 3.35.1  # Spezifische Version f端r Dart >=3.5, fix f端r _macros
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files "com.thenewkid2022.bierlounge-tracker" --type ios_app_store --create
      - name: Build IPA for TestFlight
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY  # Setze in Codemagic UI (von Apple Developer)
        submit_to_testflight: true
