workflows:
  ios-build:
    name: iOS Build for TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_VERSION: "latest"
      flutter: "3.35.1"  # Deine lokale Version – definitiv 3.35.1
      xcode: latest
      cocoapods: 1.16.2
      groups:
        - appstore_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.thenewkid2022.bierlounge-tracker
    scripts:
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Flutter Clean
        script: flutter clean --verbose
      - name: Install Flutter dependencies  # Verschoben NACH clean, um Generated.xcconfig zu regenerieren
        script: flutter pub get --verbose
      - name: Update iOS Deployment Target
        script: |
          cd ios
          # Update Podfile platform
          sed -i.bak "s/platform :ios, '14.0'/platform :ios, '15.0'/g" Podfile
          # Update post_install in Podfile
          sed -i.bak "s/'IPHONEOS_DEPLOYMENT_TARGET' = '14.0'/'IPHONEOS_DEPLOYMENT_TARGET' = '15.0'/g" Podfile
          # Update project.pbxproj
          sed -i.bak 's/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' Runner.xcodeproj/project.pbxproj
          # Update Info.plist
          sed -i.bak 's/<string>13.0<\/string>/<string>15.0<\/string>/g' Runner/Info.plist
          # Cleanup backups
          rm -f Podfile.bak Runner.xcodeproj/project.pbxproj.bak Runner/Info.plist.bak
      - name: Clean Xcode DerivedData
        script: |
          rm -rf $HOME/Library/Developer/Xcode/DerivedData/*
      - name: Debug Flutter Environment
        script: flutter doctor --verbose && flutter --version
      - name: Clean and Install Pods
        script: |
          cd ios
          pod deintegrate --verbose
          rm -rf Pods Podfile.lock
          pod install --repo-update --verbose
      - name: Fix Pod Configurations
        script: |
          cd ios/Flutter
          echo '#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"' >> Debug.xcconfig
          echo '#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"' >> Release.xcconfig
          echo '#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig"' >> Profile.xcconfig
      - name: Update Flutter iOS Config  # Bleibt nach Pods
        script: flutter build ios --config-only --release --no-codesign --verbose
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist --verbose --no-tree-shake-icons
      - name: Check Updated Files
        script: |
          ls -la ios/Runner.xcodeproj/
          cat ios/Runner.xcodeproj/project.pbxproj | grep IPHONEOS_DEPLOYMENT_TARGET
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
