workflows:
  ios-build:
    name: iOS Build for TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_VERSION: "latest"
      flutter: "3.32.8"
      xcode: latest
      cocoapods: 1.16.2
      groups:
        - appstore_credentials  # Erbt die App Store Connect Vars aus dem UI
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.thenewkid2022.bierlounge-tracker
    scripts:
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Flutter Clean
        script: flutter clean
      - name: Clean Xcode DerivedData
        script: |
          rm -rf $HOME/Library/Developer/Xcode/DerivedData/*
      - name: Debug Flutter Environment
        script: flutter doctor --verbose && flutter --version
      - name: Update Flutter iOS Config
        script: flutter build ios --config-only --release --no-codesign --verbose
      - name: Clean and Install Pods
        script: |
          cd ios
          pod deintegrate --verbose  # Hinzugefügt, um alte Pods vollständig zu entfernen
          rm -rf Pods Podfile.lock
          pod install --repo-update --verbose
      - name: Fix Pod Configurations
        script: |
          cd ios/Flutter
          echo '#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"' >> Debug.xcconfig
          echo '#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"' >> Release.xcconfig
          echo '#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig"' >> Profile.xcconfig
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist --verbose --no-tree-shake-icons
      - name: Check Updated Files
        script: |
          ls -la ios/Runner.xcodeproj/
          cat ios/Runner.xcodeproj/project.pbxproj | grep IPHONEOS_DEPLOYMENT_TARGET
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
