# Codemagic CI/CD Konfiguration für BierLounge Tracker
# Vereinfachte Konfiguration für iOS-Release-Builds
# Diese Konfiguration behebt "outdated build settings" Fehler

workflows:
  ios-release-workflow:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.thenewkid2022.bierlounge-tracker
        development_team: 767Q6NXN2U
      cocoapods: default
      ruby: default
      node: latest
    
    scripts:
      # Schritt 0: Git-Konfiguration sicherstellen
      - name: Configure Git
        script: |
          git config --global init.defaultBranch main
          git branch -M main
          # Explizit den main Branch klonen, falls master als Standard gesetzt ist
          if [ "$(git branch --show-current)" != "main" ]; then
            git checkout -b main origin/main
          fi
      
      # Schritt 1: Flutter config-only ausführen (behebt outdated settings)
      - name: Fix Flutter Build Settings
        script: |
          flutter build ios --config-only --release
      
      # Schritt 2: Flutter-Abhängigkeiten aktualisieren
      - name: Update Flutter Dependencies
        script: |
          flutter pub get
          flutter clean
          flutter pub get
      
      # Schritt 3: iOS-Abhängigkeiten installieren
      - name: Install iOS Dependencies
        script: |
          cd ios
          pod install
          cd ..
      
      # Schritt 4: iOS IPA erstellen
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    triggering:
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
      events:
        - push
    
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.cocoapods
        - ~/.cache/flutter
    
    max_build_duration: 60
    instance_type: mac_mini_m2
