workflows:
  ios-build:
    name: iOS Build for TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m1  # G체ltiger Wert: mac_mini_m1 (f체r schnelle M1-Builds)
    environment:
      vars:
        XCODE_VERSION: "15.4"
      flutter: 3.27.0  # Mit Dart 3.6 f체r Deps-Kompatibilit채t
      xcode: 15.4
      cocoapods: default
      groups:
        - appstore_credentials  # Dein Gruppenname
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files "de.bierlounge.tracker" --type ios_app_store --create
      - name: Build IPA for TestFlight
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY  # Private Key
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER  # Key ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID  # Issuer ID
        submit_to_testflight: true
