workflows:
  ios-build:
    name: iOS Build for TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_VERSION: "15.4"
      flutter: stable
      xcode: 15.4
      cocoapods: default
      groups:
        - appstore_credentials
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files "de.bierlounge.tracker" --type ios_app_store --create
      - name: Build IPA for TestFlight
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
