# Codemagic CI/CD Konfiguration für BierLounge Tracker
# Vereinfachte Konfiguration für iOS-Release-Builds
# Diese Konfiguration behebt "outdated build settings" Fehler

workflows:
  ios-build:
    name: iOS Build for TestFlight
    max_build_duration: 120
    instance_type: mac_pro_m1  # Schneller Mac für Builds
    environment:
      vars:
        XCODE_VERSION: "15.4"  # Neueste Xcode-Version für iOS
      flutter: stable  # Neueste stabile Flutter (mit Dart >=3.5 für macros)
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files "com.thenewkid2022.bierlounge-tracker" --type ios_app_store --create
      - name: Build IPA for TestFlight
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY  # Das setzt du in Codemagic UI unter Environment Variables (erhalte API-Key von Apple Developer)
        submit_to_testflight: true
