name: bierlounge_tracker
description: "BierLounge Tracker - iOS App für Verbrauchstracking und Zahlungsverwaltung"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Lokale Datenspeicherung
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Benachrichtigungen
  flutter_local_notifications: ^17.2.1

  # Externe App-Integration
  url_launcher: ^6.2.5

  # PDF-Generierung
  pdf: ^3.11.0
  printing: ^5.13.4

  # HTTP und API
  http: ^1.2.0

  # Internationalisierung - Kompatibel mit flutter_localizations
  intl: ^0.20.2

  # UUID-Generierung
  uuid: ^4.4.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: de
  arb_dir: lib/l10n
  output_dir: lib/generated


