name: bierlounge_tracker
description: "BierLounge Tracker - iOS App für Verbrauchstracking und Zahlungsverwaltung"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'  # Aktualisiert für Kompatibilität mit neueren Features, vermeidet alte SDK-Probleme
  flutter: ">=3.24.0"  # Passend zu Dart 3.5+

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Lokale Datenspeicherung (neu: sqflite statt Hive)
  sqflite: ^2.3.3
  path_provider: ^2.1.4  # Schon da, aber update für Sicherheit

  # Benachrichtigungen
  flutter_local_notifications: ^19.4.0
  flutter_local_notifications_linux: ^6.0.0
  flutter_local_notifications_platform_interface: ^9.1.0

  # Externe App-Integration
  url_launcher: ^6.3.0
  url_launcher_ios: ^6.3.4
  url_launcher_macos: ^3.2.3

  # PDF-Generierung
  pdf: ^3.11.1
  printing: ^5.13.5

  # HTTP und API
  http: ^1.2.1

  # QR-Code Generierung
  qr_flutter: ^4.1.0

  # Firebase (für Sync-Service)
  cloud_firestore: ^6.0.0
  cloud_firestore_platform_interface: ^7.0.0
  cloud_firestore_web: ^5.0.0
  firebase_core: ^4.0.0
  firebase_core_web: ^3.0.0
  _flutterfire_internals: ^1.3.60

  # Internationalisierung
  intl: ^0.20.2

  # UUID-Generierung
  uuid: ^4.4.2

  # Icons
  cupertino_icons: ^1.0.8

  # Zusätzliche Abhängigkeiten
  characters: ^1.4.1
  meta: ^1.17.0
  material_color_utilities: ^0.13.0
  path_provider_foundation: ^2.4.2
  petitparser: ^7.0.1
  shelf_web_socket: ^2.0.1
  timezone: ^0.10.1
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  
  # Test-Tools (behält nur Nötiges, entfernt Generatoren)
  test_api: ^0.7.7
  vm_service: ^15.0.2

# Dependency Overrides (entfernt unnötige, behält nur für flutter_test-Kompatibilität)
dependency_overrides:
  vm_service: 15.0.0
  test_api: 0.7.4
  meta: 1.16.0
  material_color_utilities: 0.11.1
  characters: 1.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/


