name: bierlounge_tracker
description: BierLounge Tracker – Tablet-App für Konsum, Kasse, Inventar, PDF-Reports, Offline (Hive) mit optionalem Cloud-Sync.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Offline-Speicher
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  # Utils
  intl: ^0.20.2
  uuid: ^4.4.0
  # PDF und optionales Drucken/Vorschau
  pdf: ^3.11.0
  printing: ^5.13.4
  # QR-Code für Twint-Fallback
  qr_flutter: ^4.1.0
  # Launcher für externe Apps/Deeplinks
  url_launcher: ^6.3.0
  # Benachrichtigungen
  flutter_local_notifications: ^17.2.1
  # Optionaler Cloud-Sync (deaktiviert bis konfiguriert)
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # Wir verwenden Icon-Bibliotheken; keine Bild-Assets notwendig.
  assets: []


