name: bierlounge_tracker
description: "BierLounge Tracker - iOS App für Verbrauchstracking und Zahlungsverwaltung"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Lokale Datenspeicherung
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Benachrichtigungen
  flutter_local_notifications: ^19.4.0
  flutter_local_notifications_linux: ^6.0.0
  flutter_local_notifications_platform_interface: ^9.1.0

  # Externe App-Integration
  url_launcher: ^6.3.0
  url_launcher_ios: ^6.3.4
  url_launcher_macos: ^3.2.3

  # PDF-Generierung
  pdf: ^3.11.1
  printing: ^5.13.5

  # HTTP und API
  http: ^1.2.1

  # QR-Code Generierung
  qr_flutter: ^4.1.0

  # Firebase (für Sync-Service)
  cloud_firestore: ^6.0.0
  cloud_firestore_platform_interface: ^7.0.0
  cloud_firestore_web: ^5.0.0
  firebase_core: ^4.0.0
  firebase_core_web: ^3.0.0
  _flutterfire_internals: ^1.3.60

  # Internationalisierung - Kompatibel mit flutter_localizations
  intl: ^0.20.2

  # UUID-Generierung
  uuid: ^4.4.2

  # Icons
  cupertino_icons: ^1.0.8

  # Zusätzliche Abhängigkeiten für bessere Kompatibilität
  characters: ^1.4.1
  meta: ^1.17.0
  material_color_utilities: ^0.13.0
  path_provider_foundation: ^2.4.2
  petitparser: ^7.0.1
  shelf_web_socket: ^2.0.1
  timezone: ^0.10.1
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Downgraded für Dart 3.5
  lints: ^5.1.1  # Downgraded für Dart 3.5
  hive_generator: ^2.0.1
  build_runner: ^2.4.13  # Höchste für Dart 3.5
  build_runner_core: ^7.3.2
  
  # Build-Tools
  build: ^2.4.1  # Downgraded für Dart 3.5
  build_config: ^1.2.0
  build_resolvers: ^2.4.2  # Downgraded für Dart 3.5
  source_gen: ^1.5.0  # Downgraded für Dart 3.5 und hive_generator 2.0.1
  source_helper: ^1.3.5
  
  # Analyse-Tools
  dart_style: ^3.1.2
  
  # Test-Tools
  test_api: ^0.7.7
  vm_service: ^15.0.2

# Dependency Overrides - löst Konflikte zwischen Paketen
dependency_overrides:
  # Fix für hive_generator: analyzer <7.0 (kompatibel mit Dart 3.5.1)
  analyzer: ^6.1.0
  # Fix für hive_generator: source_gen ^2.0.0 (angepasst, override entfernt da neu passt)
  # Fix für hive_generator: build ^2.4.1 (angepasst)
  build: ^2.4.1
  # Fix für hive_generator: build_config ^1.0.0
  build_config: ^1.0.0
  # Fix für hive_generator: build_resolvers ^2.4.2 (angepasst)
  build_resolvers: ^2.4.2
  # Fix für flutter_test: vm_service 15.0.0
  vm_service: 15.0.0
  # Fix für flutter_test: test_api 0.7.4
  test_api: 0.7.4
  # Fix für flutter_test: meta 1.16.0
  meta: 1.16.0
  # Fix für flutter_test: material_color_utilities 0.11.1
  material_color_utilities: 0.11.1
  # Fix für flutter_test: characters 1.4.0
  characters: 1.4.0
  # Fix für source_gen: dart_style ^2.3.8
  dart_style: ^2.3.8
  # Transitive: _fe_analyzer_shared ^87.0.0 (kompatibel mit analyzer 6.11.0)
  _fe_analyzer_shared: ^87.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/


